name: Node Continuous Integration

on: [push]

jobs: 
  push:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      - run: npm run lint
      - run: npm run test